### ISSUE TITLE
About 'Copy code'

### ISSUE THREAD

**Issue by BrandNewJimZhang** [Jamling/hexo-filter-highlight#3]
![image](https://user-images.githubusercontent.com/47765973/78207151-6898fe80-74d3-11ea-8eb4-13153b1e04a0.png)
But I do not need copy code, how to delete that?

**Comment by Jamling** [comment]
你用的不是最新版本吧？复制代码是一个剪切板的图标，在代码块右上角。

点击即可复制代码（这么好用的功能竟然不要）

可以通过CSS display:none来隐藏。参考我博客

```
.code-caption { // 当然也可以隐藏整行
    .code-caption-label {
        display:none;// 隐藏代码如下
    }

    .code-caption-copy {
        display:none;// 隐藏“复制”
    }
}
```

**Comment by BrandNewJimZhang** [comment]
哦哦查明原因了 那个剪切板图标是nova主题特有的emmm
